### ISSUE TITLE
spacing shortcut + auto update on nested groups (not symbols)

### ISSUE THREAD

**Issue by brentriddell** [DWilliames/paddy-sketch-plugin#10] opened 2018-02-08 12:24 UTC
Hi, So I can't get the spacing shortcut to ever work (control+alt+command+p), other shortcut works fine as does manually adding spacing parameters to groups. Tried removing other plugins, tried in the sketch beta, just never works. I'm in sketch 48.2 on a MacBook Pro with touch bar + High Sierra 10.13.3.

The main problem, and I'm not sure if its an issue or not, but nested groups don't update unless you select something lower down in the the group hierarchy first. Is this the intended behaviour? as it seems to work by bubbling up from what was last selected? Or should it actually update everything when you click outside (which is what I thought it was supposed to do).

video here: https://www.dropbox.com/s/ngla2oojb1eee8a/paddy%20test.mov?dl=0

sketch file here: https://www.dropbox.com/s/a1y9wtn3a7khs5i/paddy%20new%20test.sketch?dl=0

Just wondering if this is a bug or not :)

Thanks!

**Comment by luxlogica** [comment] 2018-02-10 00:34
@brentriddell In regards to the **spacing shortcut** issue: at my end, if I create a few rectangles, group them, and press ⌘+⌥+⌃+P, I get the spacing dialog. If I create a few rectangles and press the key combination without grouping them first, I get a warning message. So it seems to be working fine at my end. When you say that you "can't get the spacing shortcut to work", does it mean that nothing happens when you press the key combination, or do you get unexpected behaviour? 

In regards to the issue of **no autoupdate on group resize**, I can confirm that I can indeed reproduce it: resizing a group does not trigger the autoupdate (only editing one of its children layers). When you have multiple, deeply nested layers this is even more noticeable: the deeply nested layers will not update unless you click all the way to select one of their children - clicking on children on parent layers will not update layers down in the hierarchy. This may be intended behaviour, but we need to get confirmation from @DWilliames...

Last of all: @brentriddell, it's always a good idea to make ONE ISSUE FOR EACH PROBLEM you encounter. This report contains 2 separate problems, which would have been better to put in 2 separate issues (one for the spacing shortcut problem, one for the autoupdate on group resize). That way the plugin author can discuss and address each one of them separately, and mark each one as a bug/completed/etc., independently.

**Comment by DWilliames** [comment] 2018-02-11 08:04
Thanks @brentriddell for logging this. And thanks @luxlogica for the response too!!

1. **Spacing shortcut:** if you are talking about the keyboard shortcut not working; then I am not sure why that is. It must be something with other plugins/apps you have installed – I don't think it is an issue with Paddy. If it is just the keyboard shortcut not working, you have a few options here:

    * Use the option in the Menu bar – 'Plugins > Paddy > Spacing for selection'
    * Simply rename the layer yourself; you don't actually have to trigger the plugin with the 'Spacing for selection' action. It's just meant to make it easier to enter the values; you can name your layer for example: 'Group 2 [10v r]' to space it vertically by 10, all aligned to the right
    * Use something like [Sketch runner](sketchrunner.com) — entering 'Spacing' should bring up Paddy as an option 
    * Use the [Keys Sketch plugin](https://github.com/exevil/Keys-For-Sketch) to remap the keyboard shortcut to whatever makes sense to you.

2. **Auto update on group resize:** You are correct; this is an issue; and also the intended behaviour (to a degree). I wanted Paddy to be optimised for large documents; if you resize something that had 1,000 nested elements, some of which are Symbol instances; you'll find it will lag quite a bit. But given that most scenarios, people don't nest this deeply, I will look into fixing this.

3. **Log as separate issues:** As @luxlogica mentioned, this would be easier to log as separate issues within Github. Easier to keep track of and report against. If you can confirm that your first issue is simply with the 'Keyboard shortcut'; I will close this issue and create a new only specifically for the auto-group resizing.

Cheers, 👍 
Dave

**Comment by DWilliames** [comment] 2018-02-13 10:27
Ok @brentriddell! Good news, I think I managed to fix this so that it will attempt to update the group, only if the group resized or changed names. So it should be optimised to handle this case now.

Can you please verify in the new update (v1.0.2) that this works? If it does, then I will close this issue. 👍

**Comment by DWilliames** [comment] 2018-02-18 06:30
@brentriddell I have just released **version 1.0.3** that should make this work even better. I'll close this issue for now. If you find the issue still persists, then please re-open it. 👍

**Closed by DWilliames** 2018-02-18 06:30 UTC
Labels: bug

**Comment by brentriddell** [comment] 2018-02-19 13:00
Thanks @luxlogica and @DWilliames ... I got a horrible flu and didn't have my computer with me so I couldn't reply to all of this. But yes! the auto update seems to work great now, thank you :)
