### ISSUE TITLE
Updated to 1.0.3 and now getting odd alert from Sketch

### ISSUE THREAD

**Issue by ChrisARaymond** [DWilliames/paddy-sketch-plugin#40] opened 2018-02-21 16:54 UTC
I updated to latest version of this plugin this morning, and I keep getting a loop alert from Sketch, "Choose at least one layer to duplicate", even though I am not trying to duplicate anything. Sketch version 48.2, Mac OS Sierra. Nothing else has changed in my Sketch set up since last night.

**Comment by UXifying** [comment] 2018-02-22 11:21
Ive just installed this for the first time and I'm getting the same alert. I seem to get it when deselecting any layer. Otherwise I like the the plugin and have achieved exactly what I wanted.
Sketch version 48.2, Mac OS High Sierra.

**Comment by boxzakamads** [comment] 2018-02-22 11:36
Same error here. MacOS High Sierra (10.13.2) and Sketch 48.2 (47327).

Any solutions?

**Comment by ChrisARaymond** [comment] 2018-02-22 13:52
I reverted to the last version of Paddy, and no problems.

**Comment by JWhiteUX** [comment] 2018-02-22 18:34
Same problem here. I disabled Paddy and the error has subsided. 

https://www.dropbox.com/s/ka0ztldlhrkyq88/duplicate-bug.mov?dl=0

**Comment by DWilliames** [comment] 2018-02-23 09:18
Thanks all for highlighting this — I'm gonna mark this as a duplicate of https://github.com/DWilliames/paddy-sketch-plugin/issues/18; and move all further conversations in there. Thanks for your patience as I try and figure out why Craft is causing this conflict.

**Closed by DWilliames** 2018-02-23 09:18 UTC
Labels: duplicate
