### ISSUE TITLE
[Bug] Constantly asking to update instances without changes

### ISSUE THREAD

**Issue by kameronahler** [DWilliames/paddy-sketch-plugin#75] opened 2018-03-09 20:48 UTC
<img width="761" alt="screen shot 2018-03-09 at 1 50 05 pm" src="https://user-images.githubusercontent.com/16659448/37229306-d2f2c2b0-23a0-11e8-96df-73782b431af8.png">
#### Actual behavior:
http://recordit.co/jPvddsFWUD

Paddy seems to be flipping out whenever I interact with symbols. I am not changing anything, just selecting a symbol, then clicking off the artboard.

#### Steps to reproduce:
Can't attach - sorry. Hopefully it's user error. I'm clicking on a symbol that is being used elsewhere with Paddy. I am not making any changes. Click off symbol and get a message saying that instances need updating. Updating does not solve the problem, continues to happen.

**Comment by DWilliames** [comment] 2018-03-10 22:39
Yeah this seems like an issue with Paddy, not user error. Sorry :( 
Thanks for the heads up @kameronahler!

**Comment by midocom** [comment] 2018-03-11 09:37
![image](https://user-images.githubusercontent.com/726724/37251870-822d7fb0-2520-11e8-9f42-c8b301846039.png)
Paddy seems to be flipping out whenever I interact with symbols. I am not changing anything, just selecting a symbol, then clicking off the artboard.

Steps to reproduce:
Can't attach - sorry. Hopefully it's user error. I'm clicking on a symbol that is being used elsewhere with Paddy. I am not making any changes. Click off symbol and get a message saying that instances need updating. Updating does not solve the problem, continues to happen.

**Comment by illustree** [comment] 2018-03-12 13:06
hey guys, please fix that one ... need to delete paddy meanwhile because it is impossible to work with this dialog appearing the whole time :--( can't wait for a fix, thanks

**Comment by bwilkn** [comment] 2018-03-12 23:06
Yeah, this is a biggy and occurs multiple times a minute.

**Comment by mattkast** [comment] 2018-03-13 19:25
I've also been experiencing this, had to delete paddy as it was a major hindrance!

**Comment by matt-bailey** [comment] 2018-03-13 20:36
I'm experiencing this too (v1.0.6) - Paddy wants to constantly update when working on the Symbols page. I've disabled Paddy for now until a fix has been released.

**Comment by lyapustin** [comment] 2018-03-14 13:13
I have the same issue. But it seems it does so because one of the layers in the group have a separate L in the name, like, “15 Blue L”. Maybe plugin just should ignore everything outside the []?

**Comment by quitefrank** [comment] 2018-03-15 14:00
Same issue here

**Comment by DWilliames** [comment] 2018-03-18 03:28
I can appreciate how annoying this alert must be! I'm having trouble with the logic surrounding it; so I have decided to remove it entirely. 👍 

Will be fixed in the next release.

**Comment by DWilliames** [comment] 2018-03-18 04:25
This should now be fixed v1.0.7 – if you find it still persists; then please re-open this issue.

**Closed by DWilliames** 2018-03-18 04:25 UTC
Labels: bug, fixed in next release
