### ISSUE TITLE
Modal window "Please select at least one layer to duplicate" keep poping.

### ISSUE THREAD

**Issue by hdche** [DWilliames/paddy-sketch-plugin#34] opened 2018-02-19 13:16 UTC
![screen shot 2018-02-19 at 13 31 16](https://user-images.githubusercontent.com/22611248/36379572-674c32f0-157f-11e8-8320-b4f382d50f05.png)

version 1.0.3.

**Comment by panchovm** [comment] 2018-02-19 14:17
I have the same issue. It's impossible to close the app. Thank you for reporting

**Comment by brandensilva** [comment] 2018-02-19 22:36
Unfortunately I've had to disable the plugin until this gets fixed because it continues to interrupt the workflow.

**Comment by Croops** [comment] 2018-02-19 23:02
Yup I get the same error. Only started happening once I installed the Paddy plug in.

**Comment by PatrykLes** [comment] 2018-02-20 09:35
Same here. Please help!

**Comment by sherifsaleh** [comment] 2018-02-20 12:18
same problem, it just went away when i disabled the plugin.
https://sketchtalk.io/discussion/3044/error-message-please-select-at-least-one-layer-to-duplicate

**Comment by deezinerUK** [comment] 2018-02-20 14:18
Yep - same here. Disabled plugin for now.

**Comment by mathieudutour** [comment] 2018-02-22 08:53
duplicate of https://github.com/DWilliames/paddy-sketch-plugin/issues/18

**Comment by DWilliames** [comment] 2018-02-23 09:18
Thanks all for highlighting this — I'm gonna mark this as a duplicate of https://github.com/DWilliames/paddy-sketch-plugin/issues/18; and move all further conversations in there. Thanks for your patience as I try and figure out why Craft is causing this conflict.

**Closed by DWilliames** 2018-02-23 09:18 UTC
