### ISSUE TITLE
Auto-update doesn't work with duplicate and delete

### ISSUE THREAD

**Issue by RaphyRaph** [DWilliames/paddy-sketch-plugin#7] opened 2018-02-07 13:37 UTC
When duplicating or deleting elements in a auto-spaced and auto-padded group, the spacing update doesn't happen until you click outside the group.

**Comment by luxlogica** [comment] 2018-02-08 01:44
This seems to be the intended behaviour, as per the ReadMe:

> [...] **Automatic**: Most other plugins require a keyboard shortcut for them to be applied, or re-applied. This is all done automatically as you manipulate your layers; simply deselect everything, and will be updated.

**Comment by DWilliames** [comment] 2018-02-08 11:24
Yeah. Thanks @luxlogica, that is correct.

Unfortunately there's a limitation in how the plugin is triggered. It uses Sketch's 'selection changed' trigger; and will only update if the selection changes to nothing — this is to keep the plugin optimised. Otherwise, the plugin would not be able to handle large documents when you drag-select a bunch of layers, because every time the 'selection-changed' it would try to re-calculate everything.

I know it is not ideal. I'll see if I can find a good optimal solution. But until then, this is the intended behaviour, given the limitation.

**Comment by DWilliames** [comment] 2018-02-13 10:24
A slight update on this @RaphyRaph — whilst it doesn't work for duplicating; I just released v1.0.2... if you delete a 'group' layer, that is within a group with spacing, it should automatically update now.

**Comment by DWilliames** [comment] 2018-02-18 06:28
@RaphyRaph I have just released **version 1.0.3** that should now make this work for duplicating or deleting layers. I'll close this issue for now. If you fin the issue still persists, then please re-open it. 👍

**Closed by DWilliames** 2018-02-18 06:28 UTC
Labels: parked
